# Generated by Django 3.2.9 on 2023-12-16 09:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^AC[0-9]{10}', 'invalid AC ID')])),
                ('name', models.CharField(max_length=200)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Db',
            fields=[
                ('cmdbid', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')])),
                ('name', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=25)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('cmdbid', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')])),
                ('name', models.CharField(max_length=80)),
                ('product', models.CharField(max_length=50)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('cmdbid', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')])),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=25)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
                ('fk_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.host')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_section', models.CharField(max_length=40)),
                ('parameter', models.CharField(max_length=80)),
                ('parameter_index', models.IntegerField()),
                ('value', models.CharField(max_length=200, null=True)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instance')),
            ],
        ),
        migrations.CreateModel(
            name='HostParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_section', models.CharField(max_length=40)),
                ('parameter', models.CharField(max_length=80)),
                ('parameter_index', models.IntegerField()),
                ('value', models.CharField(max_length=200, null=True)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.host')),
            ],
        ),
        migrations.CreateModel(
            name='DbParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_section', models.CharField(max_length=40)),
                ('parameter', models.CharField(max_length=80)),
                ('parameter_index', models.IntegerField()),
                ('value', models.CharField(max_length=200, null=True)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.db')),
            ],
        ),
        migrations.AddField(
            model_name='db',
            name='fk_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instance'),
        ),
        migrations.CreateModel(
            name='AccountParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_section', models.CharField(max_length=40)),
                ('parameter', models.CharField(max_length=80)),
                ('parameter_index', models.IntegerField()),
                ('value', models.CharField(max_length=200, null=True)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='fk_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.db'),
        ),
    ]
